name: CI/CD with Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # Docker build and push step
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5  # Corrected action version
        with:
          image: sakiburrahman07/spring-boot-ci-cd  # Specify your repository/image name
          tags: latest  # Specify tags you want to push
          registry: docker.io  # Replace with your registry URL (e.g., Docker Hub or custom registry)
          dockerfile: Dockerfile  # Path to the Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker registry username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker registry password from GitHub Secrets

  deploys:
    needs: build  # 'deploys' job depends on 'build' job
    runs-on: ubuntu-latest

    steps:
      - name: Login to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull sakiburrahman07/spring-boot-ci-cd:latest  # Match this to the image built in the 'build' job
            docker stop spring-boot-ci-cd || true
            docker rm spring-boot-ci-cd || true
            docker run -d -p 8080:80 --name spring-boot-ci-cd sakiburrahman07/spring-boot-ci-cd:latest  # Match image name
